name: typenums
version: 0.1.1
synopsis: Type level numbers using existing Nat functionality
description: >
  Type level numbers using existing Nat functionality.
  Uses kind-polymorphic typeclasses and type families to
  facilitate more general code compatible with existing
  code using type-level Naturals.
category: Data
github: adituv/typenums
license: BSD3
tested-with: GHC == 8.0.1, GHC == 8.0.2, GHC == 8.2.2, GHC == 8.4.3
author: AdituV
maintainer: aditu.venyhandottir@gmail.com
copyright: 2018 Iris Ward
extra-doc-files:
- CHANGELOG.md
- README.md

ghc-options: -Wall

dependencies:
  - base > 4.9 && < 5.0

library:
  other-modules:
    - Data.TypeNums.Arithmetic
    - Data.TypeNums.Comparison
    - Data.TypeNums.Equality
  source-dirs: src

tests:
  typenums-tests:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - typenums
      - hspec >= 2.0
      - QuickCheck >= 2.0
    ghc-options: -Wno-all
